# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Configurar JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: 11
    - name: Compilar y empaquetar con Maven
      run: mvn -B package --file pom.xml
    - name: Subir.jar
    - uses: actions/upload-artifact@v1
      with:
         name: backend
         path: target/backend-0.0.1.jar
    
